/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Keyword } from "./Keyword";
import { KeywordCountArgs } from "./KeywordCountArgs";
import { KeywordFindManyArgs } from "./KeywordFindManyArgs";
import { KeywordFindUniqueArgs } from "./KeywordFindUniqueArgs";
import { CreateKeywordArgs } from "./CreateKeywordArgs";
import { UpdateKeywordArgs } from "./UpdateKeywordArgs";
import { DeleteKeywordArgs } from "./DeleteKeywordArgs";
import { KeywordService } from "../keyword.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Keyword)
export class KeywordResolverBase {
  constructor(
    protected readonly service: KeywordService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "read",
    possession: "any",
  })
  async _keywordsMeta(
    @graphql.Args() args: KeywordCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Keyword])
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "read",
    possession: "any",
  })
  async keywords(
    @graphql.Args() args: KeywordFindManyArgs
  ): Promise<Keyword[]> {
    return this.service.keywords(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Keyword, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "read",
    possession: "own",
  })
  async keyword(
    @graphql.Args() args: KeywordFindUniqueArgs
  ): Promise<Keyword | null> {
    const result = await this.service.keyword(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Keyword)
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "create",
    possession: "any",
  })
  async createKeyword(
    @graphql.Args() args: CreateKeywordArgs
  ): Promise<Keyword> {
    return await this.service.createKeyword({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Keyword)
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "update",
    possession: "any",
  })
  async updateKeyword(
    @graphql.Args() args: UpdateKeywordArgs
  ): Promise<Keyword | null> {
    try {
      return await this.service.updateKeyword({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Keyword)
  @nestAccessControl.UseRoles({
    resource: "Keyword",
    action: "delete",
    possession: "any",
  })
  async deleteKeyword(
    @graphql.Args() args: DeleteKeywordArgs
  ): Promise<Keyword | null> {
    try {
      return await this.service.deleteKeyword(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
